server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - "configuration/UAT"
            - "configuration/PROD"

  profiles:
    active:
      - native

logging.level.: DEBUG